const EXTENSION_MAP = {
  bash: "sh",
  c: "c",
  cpp: "cpp",
  "cpp17": "cpp",
  csharp: "cs",
  go: "go",
  java: "java",
  javascript: "js",
  kotlin: "kt",
  php: "php",
  python: "py",
  ruby: "rb",
  rust: "rs",
  scala: "scala",
  swift: "swift",
  typescript: "ts",
  r: "r",
  sql: "sql",
  perl: "pl",
  lua: "lua",
  dart: "dart",
};
export default EXTENSION_MAP