const TITLE_TERM = [
    {
        term: {
            title: "Học kỳ 1",
            NumberOfCredits: "11",
        },

        obligatory: {
            title: "Học phần bắt buộc",
            NumberOfCredits: "7",
            section: [
                {
                    nameCourse: 'Thiết kế đồ họa 1',
                    code: "0101082452",
                    typeOf: "",
                    NumberOfCredits: "2(1,1,4)",
                    LT: "15",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Thực tế',
                    code: "0101082774",
                    typeOf: "",
                    NumberOfCredits: "5(1,4,10)",
                    LT: "15",
                    TH: "60",
                    form: "Báo cáo",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        },
        selfSelect: {
            title: "Học phần tự chọn",
            NumberOfCredits: "4",
            section: [
                {
                    nameCourse: 'Kỹ năng giao tiếp',
                    code: "0101083021",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "1",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Kỹ năng giải quyết vấn đề',
                    code: "0101083022",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "1",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Kỹ năng thuyết trình',
                    code: "0101083023",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "1",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Kỹ năng tư duy sáng tạo',
                    code: "0101083024",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "1",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Quản trị học',
                    code: "0101081079",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "2",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Khởi nghiệp',
                    code: "0101082903",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "0",
                    form: "Báo cáo",
                    typeOfLecture: "",
                    group: "2",
                    NumberTC: "",
                }
            ]
        }
    },
    {
        term: {
            title: "Học kỳ 2",
            NumberOfCredits: "12",
        },

        obligatory: {
            title: "Học phần bắt buộc",
            NumberOfCredits: "9",
            section: [
                {
                    nameCourse: 'Tiếng Anh 1 *',
                    code: "0101081681",
                    typeOf: "",
                    NumberOfCredits: "3(3, 0, 6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Giáo dục thể chất 1 *',
                    code: "0101081704",
                    typeOf: "",
                    NumberOfCredits: "1(0, 1, 2)",
                    LT: "0",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Tin học đại cương',
                    code: "0101082534",
                    typeOf: "",
                    NumberOfCredits: "3(2,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Toán cao cấp 1',
                    code: "0101082538",
                    typeOf: "",
                    NumberOfCredits: "3(3,0,6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Triết học Mác - Lê Nin',
                    code: "	0101082683",
                    typeOf: "",
                    NumberOfCredits: "3(3,0,6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        },
        selfSelect: {
            title: "Học phần tự chọn",
            NumberOfCredits: "4",
            section: [
                {
                    nameCourse: 'Java cơ bản',
                    code: "0101081958",
                    typeOf: "",
                    NumberOfCredits: "3(2,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Phương pháp lập trình (C++)',
                    code: "0101082456",
                    typeOf: "",
                    NumberOfCredits: "3(2,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        }
    },
    {
        term: {
            title: "Học kỳ 3",
            NumberOfCredits: "12",
        },

        obligatory: {
            title: "Học phần bắt buộc",
            NumberOfCredits: "12",
            section: [
                {
                    nameCourse: 'Pháp luật đại cương',
                    code: "0101010032",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Cấu trúc dữ liệu và giải thuật',
                    code: "0101081389",
                    typeOf: "",
                    NumberOfCredits: "3(2,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Tiếng Anh 2 *',
                    code: "0101081682",
                    typeOf: "",
                    NumberOfCredits: "3(3, 0, 6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Vật lý',
                    code: "0101082022",
                    typeOf: "",
                    NumberOfCredits: "3(2, 1, 60)",
                    LT: "30",
                    TH: "30",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Toán cao cấp 2',
                    code: "0101082539",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Kinh tế chính trị Mác - Lê Nin',
                    code: "0101082684",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        },
        selfSelect: {
            title: "",
            NumberOfCredits: "",
            section: [

            ]
        }
    },
    {
        term: {
            title: "Học kỳ 4",
            NumberOfCredits: "10",
        },

        obligatory: {
            title: "Học phần bắt buộc",
            NumberOfCredits: "10",
            section: [
                {
                    nameCourse: 'Kiến trúc máy tính',
                    code: "0101020046",
                    typeOf: "",
                    NumberOfCredits: "3(3,0,6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Mạng máy tính',
                    code: "0101081511",
                    typeOf: "",
                    NumberOfCredits: "3(2, 1, 6)",
                    LT: "30",
                    TH: "30",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Phương pháp nghiên cứu khoa học',
                    code: "0101081575",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Tiếng Anh 3 *',
                    code: "0101081683",
                    typeOf: "",
                    NumberOfCredits: "3(3, 0, 6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Giáo dục thể chất 2 *',
                    code: "0101081705",
                    typeOf: "",
                    NumberOfCredits: "1(0, 1, 2)",
                    LT: "0",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Chủ nghĩa xã hội khoa học',
                    code: "0101082685",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        },
        selfSelect: {
            title: "",
            NumberOfCredits: "",
            section: [

            ]
        }
    },
    {
        term: {
            title: "Học kỳ 5",
            NumberOfCredits: "10",
        },

        obligatory: {
            title: "Học phần bắt buộc",
            NumberOfCredits: "8",
            section: [
                {
                    nameCourse: 'Phát triển Web',
                    code: "0101081546",
                    typeOf: "",
                    NumberOfCredits: "3(2, 1, 6)",
                    LT: "30",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Tiếng Anh 4 *',
                    code: "0101081684",
                    typeOf: "",
                    NumberOfCredits: "3(3, 0, 6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Giáo dục thể chất 3 *',
                    code: "0101081706",
                    typeOf: "",
                    NumberOfCredits: "1(0, 1, 2)",
                    LT: "0",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Hệ cơ sở dữ liệu',
                    code: "0101082494",
                    typeOf: "",
                    NumberOfCredits: "3(2,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Lịch sử Đảng CSVN',
                    code: "	0101082686",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        },
        selfSelect: {
            title: "Học phần tự chọn",
            NumberOfCredits: "2",
            section: [
                {
                    nameCourse: 'Phương pháp tính',
                    code: "0101081099",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Hàm biến phức và phép BĐ Laplace',
                    code: "0101081107",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Xác suất thống kê',
                    code: "0101081115",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        }
    },
    {
        term: {
            title: "Học kỳ 6",
            NumberOfCredits: "8",
        },

        obligatory: {
            title: "Học phần bắt buộc",
            NumberOfCredits: "6",
            section: [
                {
                    nameCourse: 'Tư tưởng Hồ Chí Minh',
                    code: "0101010038",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Giáo dục quốc phòng - an ninh *',
                    code: "0101081134",
                    typeOf: "",
                    NumberOfCredits: "8(6, 2, 16)",
                    LT: "125",
                    TH: "40",
                    form: "Tự luận",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Tiếng Anh 5 *',
                    code: "0101081685",
                    typeOf: "",
                    NumberOfCredits: "3(3, 0, 6)",
                    LT: "45",
                    TH: "0",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Kỹ thuật soạn thảo văn bản, trình bày báo cáo',
                    code: "0101082455",
                    typeOf: "",
                    NumberOfCredits: "2(1,1,4)",
                    LT: "15",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Đồ án học phần 1',
                    code: "0101082495",
                    typeOf: "",
                    NumberOfCredits: "2(0,2,4)",
                    LT: "0",
                    TH: "60",
                    form: "Bảo vệ",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        },
        selfSelect: {
            title: "Học phần tự chọn",
            NumberOfCredits: "2",
            section: [
                {
                    nameCourse: 'Kỹ năng làm việc nhóm',
                    code: "0101083026",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Kỹ năng quản lý thời gian',
                    code: "0101083027",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Kỹ năng tìm việc',
                    code: "0101083028",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
                ,
                {
                    nameCourse: 'Kỹ năng phỏng vấn',
                    code: "0101083029",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        }
    },
    {
        term: {
            title: "Học kỳ 7",
            NumberOfCredits: "16",
        },

        obligatory: {
            title: "Học phần bắt buộc",
            NumberOfCredits: "7",
            section: [
                {
                    nameCourse: 'Lập trình hướng đối tượng',
                    code: "0101081499",
                    typeOf: "",
                    NumberOfCredits: "3(2,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Tiếng Anh 6 *',
                    code: "0101081709",
                    typeOf: "",
                    NumberOfCredits: "3(3, 0, 6)",
                    LT: "45",
                    TH: "0",
                    form: "Tự luận",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Thực tập cơ sở',
                    code: "0101082453",
                    typeOf: "",
                    NumberOfCredits: "4(0,4,10)",
                    LT: "",
                    TH: "120",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },

            ]
        },
        selfSelect: {
            title: "Học phần tự chọn",
            NumberOfCredits: "9",
            section: [
                {
                    nameCourse: 'Tiếng Anh kỹ thuật',
                    code: "0101081133",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Lịch sử mỹ thuật',
                    code: "0101082940",
                    typeOf: "",
                    NumberOfCredits: "3(3,0,6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Nguyên lý thống kê',
                    code: "0101081085",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "1",
                    NumberTC: "5",
                }
                ,
                {
                    nameCourse: 'Kỹ thuật điện tử',
                    code: "0101081143",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "1",
                    NumberTC: "5",
                },
                {
                    nameCourse: 'Nguyên lý kế toán',
                    code: "0101081199",
                    typeOf: "",
                    NumberOfCredits: "3(3, 0, 6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "1",
                    NumberTC: "5",
                },
                {
                    nameCourse: 'Hệ thống thông tin quản lý',
                    code: "0101081466",
                    typeOf: "",
                    NumberOfCredits: "3(3, 0, 6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "1",
                    NumberTC: "5",
                },
                {
                    nameCourse: 'Lập trình Windows',
                    code: "0101081503",
                    typeOf: "",
                    NumberOfCredits: "3(2, 1, 6)",
                    LT: "30",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "1",
                    NumberTC: "5",
                },
                {
                    nameCourse: 'Thiết kế đồ hoạ 2',
                    code: "0101081557",
                    typeOf: "",
                    NumberOfCredits: "2(1, 1, 4)",
                    LT: "15",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "1",
                    NumberTC: "5",
                },
                {
                    nameCourse: 'Tin học chuyên ngành Đồ họa',
                    code: "0101081968",
                    typeOf: "",
                    NumberOfCredits: "2(1, 1, 4)",
                    LT: "15",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "1",
                    NumberTC: "5",
                },
                {
                    nameCourse: 'Luật xa gần',
                    code: "0101082513",
                    typeOf: "",
                    NumberOfCredits: "3(3,0,6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "1",
                    NumberTC: "5",
                },
                {
                    nameCourse: 'Lịch sử thiết kế đồ họa',
                    code: "0101082458",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "35",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "2",
                    NumberTC: "2",
                }
            ]
        }
    },
    {
        term: {
            title: "Học kỳ 8",
            NumberOfCredits: "7",
        },

        obligatory: {
            title: "Học phần bắt buộc",
            NumberOfCredits: "5",
            section: [
                {
                    nameCourse: 'Tiếng Anh B1.1',
                    code: "0101081887",
                    typeOf: "",
                    NumberOfCredits: "3(3,0,6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Linux và phần mềm mã nguồn mở',
                    code: "0101082459",
                    typeOf: "",
                    NumberOfCredits: "2(1,1,4)",
                    LT: "15",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }

            ]
        },
        selfSelect: {
            title: "Học phần tự chọn",
            NumberOfCredits: "2",
            section: [
                {
                    nameCourse: 'Văn hóa doanh nghiệp',
                    code: "0101081568",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Tâm lý học quản lý',
                    code: "0101082911",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        }
    },
    {
        term: {
            title: "Học kỳ 9",
            NumberOfCredits: "12",
        },

        obligatory: {
            title: "Học phần bắt buộc",
            NumberOfCredits: "12",
            section: [
                {
                    nameCourse: 'Hệ điều hành',
                    code: "0101081447",
                    typeOf: "",
                    NumberOfCredits: "3(3,0,6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Toán rời rạc',
                    code: "0101081540",
                    typeOf: "",
                    NumberOfCredits: "3(3,0,6)",
                    LT: "15",
                    TH: "30",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Phát triển Web nâng cao',
                    code: "0101081547",
                    typeOf: "",
                    NumberOfCredits: "3(2,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Bảo vệ",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Tiếng anh B1.2',
                    code: "0101081888",
                    typeOf: "",
                    NumberOfCredits: "3(3,0,6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }

            ]
        },
        selfSelect: {
            title: "",
            NumberOfCredits: "",
            section: [

            ]
        }
    },
    {
        term: {
            title: "Học kỳ 10",
            NumberOfCredits: "14",
        },

        obligatory: {
            title: "Học phần bắt buộc",
            NumberOfCredits: "11",
            section: [
                {
                    nameCourse: 'Đồ án học phần 2',
                    code: "0101081415",
                    typeOf: "",
                    NumberOfCredits: "2(0, 2, 4)",
                    LT: "0",
                    TH: "30",
                    form: "Bảo vệ",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Phân tích thiết kế hệ thống',
                    code: "0101081533",
                    typeOf: "",
                    NumberOfCredits: "3(3, 0, 6)",
                    LT: "45",
                    TH: "0",
                    form: "Bảo vệ",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Truyền số liệu',
                    code: "0101081545",
                    typeOf: "",
                    NumberOfCredits: "3(3, 0, 6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Lập trình Python',
                    code: "0101083012",
                    typeOf: "",
                    NumberOfCredits: "3(2,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }

            ]
        },
        selfSelect: {
            title: "Học phần tự chọn",
            NumberOfCredits: "3",
            section: [
                {
                    nameCourse: 'Vi xử lý',
                    code: "0101081283",
                    typeOf: "",
                    NumberOfCredits: "3(3, 0, 6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Lập trình mạng',
                    code: "0101081501",
                    typeOf: "",
                    NumberOfCredits: "3(2, 1, 6)",
                    LT: "30",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Quản lý chất lượng phần mềm',
                    code: "0101081550",
                    typeOf: "",
                    NumberOfCredits: "3(3, 0, 6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Java nâng cao',
                    code: "0101081964",
                    typeOf: "",
                    NumberOfCredits: "3(2,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        }
    },
    {
        term: {
            title: "Học kỳ 11",
            NumberOfCredits: "16",
        },

        obligatory: {
            title: "Học phần bắt buộc",
            NumberOfCredits: "13",
            section: [
                {
                    nameCourse: 'Trí tuệ nhân tạo',
                    code: "0101081543",
                    typeOf: "",
                    NumberOfCredits: "3(3, 0, 6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Xử lý ảnh',
                    code: "0101081549",
                    typeOf: "",
                    NumberOfCredits: "3(3,0,6)",
                    LT: "45",
                    TH: "0",
                    form: "Bảo vệ",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Thực tập kỹ thuật',
                    code: "0101082942",
                    typeOf: "",
                    NumberOfCredits: "4(0,4,8)",
                    LT: "0",
                    TH: "120",
                    form: "Báo cáo",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Hệ quản trị cơ sở dữ liệu',
                    code: "0101082943",
                    typeOf: "",
                    NumberOfCredits: "3(2,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }

            ]
        },
        selfSelect: {
            title: "Học phần tự chọn",
            NumberOfCredits: "3",
            section: [
                {
                    nameCourse: 'Chương trình dịch',
                    code: "0101081398",
                    typeOf: "",
                    NumberOfCredits: "3(3, 0, 6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Lập trình Windows nâng cao',
                    code: "0101081505",
                    typeOf: "",
                    NumberOfCredits: "3(2, 1, 6)",
                    LT: "30",
                    TH: "30",
                    form: "Bảo vệ",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Truyền thông đa phương tiện',
                    code: "0101082953",
                    typeOf: "",
                    NumberOfCredits: "3(2,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        }
    },
    {
        term: {
            title: "Học kỳ 12",
            NumberOfCredits: "14",
        },

        obligatory: {
            title: "Học phần bắt buộc",
            NumberOfCredits: "11",
            section: [
                {
                    nameCourse: 'Học máy',
                    code: "0101081965",
                    typeOf: "",
                    NumberOfCredits: "3(3, 0, 6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Thực tập tốt nghiệp kỹ sư',
                    code: "0101082948",
                    typeOf: "",
                    NumberOfCredits: "8(0,8,16)",
                    LT: "0",
                    TH: "240",
                    form: "Báo cáo",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        },
        selfSelect: {
            title: "Học phần tự chọn",
            NumberOfCredits: "3",
            section: [
                {
                    nameCourse: 'Công nghệ phần mềm',
                    code: "0101081963",
                    typeOf: "",
                    NumberOfCredits: "3(3,0,6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Chuyên đề',
                    code: "0101081992",
                    typeOf: "",
                    NumberOfCredits: "3(0,3,6)",
                    LT: "0",
                    TH: "90",
                    form: "Bảo vệ",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Lập trình cho thiết bị di động',
                    code: "0101082460",
                    typeOf: "",
                    NumberOfCredits: "3(2,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        }
    },
    {
        term: {
            title: "Học kỳ 13",
            NumberOfCredits: "10",
        },

        obligatory: {
            title: "Học phần bắt buộc",
            NumberOfCredits: "11",
            section: [
                {
                    nameCourse: 'Đồ án tốt nghiệp kỹ sư',
                    code: "0101082949",
                    typeOf: "",
                    NumberOfCredits: "10(0,10,0)",
                    LT: "0",
                    TH: "150",
                    form: "Bảo vệ",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        },
        selfSelect: {
            title: "",
            NumberOfCredits: "",
            section: [

            ]
        }
    },


]
export default TITLE_TERM