const TERM_DESIGN = [
    {
        term: {
            title: "Học kỳ 1",
            NumberOfCredits: "11",
        },

        obligatory: {
            title: "Học phần bắt buộc",
            NumberOfCredits: "7",
            section: [
                {
                    nameCourse: 'Thiết kế đồ họa 1',
                    code: "0101082452",
                    typeOf: "",
                    NumberOfCredits: "2(1,1,4)",
                    LT: "15",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Thực tế',
                    code: "0101082774",
                    typeOf: "",
                    NumberOfCredits: "5(1,4,10)",
                    LT: "15",
                    TH: "60",
                    form: "Báo cáo",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        },
        selfSelect: {
            title: "Học phần tự chọn",
            NumberOfCredits: "4",
            section: [
                {
                    nameCourse: 'Kỹ năng giao tiếp',
                    code: "0101083021",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "1",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Kỹ năng giải quyết vấn đề',
                    code: "0101083022",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "1",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Kỹ năng thuyết trình',
                    code: "0101083023",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "1",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Kỹ năng tư duy sáng tạo',
                    code: "0101083024",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "1",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Quản trị học',
                    code: "0101081079",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "2",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Khởi nghiệp',
                    code: "0101082903",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "0",
                    form: "Báo cáo",
                    typeOfLecture: "",
                    group: "2",
                    NumberTC: "",
                }
            ]
        }
    },
    {
        term: {
            title: "Học kỳ 2",
            NumberOfCredits: "12",
        },

        obligatory: {
            title: "Học phần bắt buộc",
            NumberOfCredits: "9",
            section: [
                {
                    nameCourse: 'Tiếng Anh 1 *',
                    code: "0101081681",
                    typeOf: "",
                    NumberOfCredits: "3(3, 0, 6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Giáo dục thể chất 1 *',
                    code: "0101081704",
                    typeOf: "",
                    NumberOfCredits: "1(0, 1, 2)",
                    LT: "0",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Tin học đại cương',
                    code: "0101082534",
                    typeOf: "",
                    NumberOfCredits: "3(2,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Toán cao cấp 1',
                    code: "0101082538",
                    typeOf: "",
                    NumberOfCredits: "3(3,0,6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Triết học Mác - Lê Nin',
                    code: "	0101082683",
                    typeOf: "",
                    NumberOfCredits: "3(3,0,6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        },
        selfSelect: {
            title: "Học phần tự chọn",
            NumberOfCredits: "4",
            section: [
                {
                    nameCourse: 'Java cơ bản',
                    code: "0101081958",
                    typeOf: "",
                    NumberOfCredits: "3(2,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Phương pháp lập trình (C++)',
                    code: "0101082456",
                    typeOf: "",
                    NumberOfCredits: "3(2,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        }
    },
    {
        term: {
            title: "Học kỳ 3",
            NumberOfCredits: "12",
        },

        obligatory: {
            title: "Học phần bắt buộc",
            NumberOfCredits: "12",
            section: [
                {
                    nameCourse: 'Pháp luật đại cương',
                    code: "0101010032",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Cấu trúc dữ liệu và giải thuật',
                    code: "0101081389",
                    typeOf: "",
                    NumberOfCredits: "3(2,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Tiếng Anh 2 *',
                    code: "0101081682",
                    typeOf: "",
                    NumberOfCredits: "3(3, 0, 6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Vật lý',
                    code: "0101082022",
                    typeOf: "",
                    NumberOfCredits: "3(2, 1, 60)",
                    LT: "30",
                    TH: "30",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Toán cao cấp 2',
                    code: "0101082539",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Kinh tế chính trị Mác - Lê Nin',
                    code: "0101082684",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        },
        selfSelect: {
            title: "",
            NumberOfCredits: "",
            section: [

            ]
        }
    },
    {
        term: {
            title: "Học kỳ 4",
            NumberOfCredits: "10",
        },

        obligatory: {
            title: "Học phần bắt buộc",
            NumberOfCredits: "10",
            section: [
                {
                    nameCourse: 'Kiến trúc máy tính',
                    code: "0101020046",
                    typeOf: "",
                    NumberOfCredits: "3(3,0,6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Mạng máy tính',
                    code: "0101081511",
                    typeOf: "",
                    NumberOfCredits: "3(2, 1, 6)",
                    LT: "30",
                    TH: "30",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Phương pháp nghiên cứu khoa học',
                    code: "0101081575",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Tiếng Anh 3 *',
                    code: "0101081683",
                    typeOf: "",
                    NumberOfCredits: "3(3, 0, 6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Giáo dục thể chất 2 *',
                    code: "0101081705",
                    typeOf: "",
                    NumberOfCredits: "1(0, 1, 2)",
                    LT: "0",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Chủ nghĩa xã hội khoa học',
                    code: "0101082685",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        },
        selfSelect: {
            title: "",
            NumberOfCredits: "",
            section: [

            ]
        }
    },
    {
        term: {
            title: "Học kỳ 5",
            NumberOfCredits: "10",
        },

        obligatory: {
            title: "Học phần bắt buộc",
            NumberOfCredits: "8",
            section: [
                {
                    nameCourse: 'Phát triển Web',
                    code: "0101081546",
                    typeOf: "",
                    NumberOfCredits: "3(2, 1, 6)",
                    LT: "30",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Tiếng Anh 4 *',
                    code: "0101081684",
                    typeOf: "",
                    NumberOfCredits: "3(3, 0, 6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Giáo dục thể chất 3 *',
                    code: "0101081706",
                    typeOf: "",
                    NumberOfCredits: "1(0, 1, 2)",
                    LT: "0",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Hệ cơ sở dữ liệu',
                    code: "0101082494",
                    typeOf: "",
                    NumberOfCredits: "3(2,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Lịch sử Đảng CSVN',
                    code: "	0101082686",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        },
        selfSelect: {
            title: "Học phần tự chọn",
            NumberOfCredits: "2",
            section: [
                {
                    nameCourse: 'Phương pháp tính',
                    code: "0101081099",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Hàm biến phức và phép BĐ Laplace',
                    code: "0101081107",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Xác suất thống kê',
                    code: "0101081115",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        }
    },
    {
        term: {
            title: "Học kỳ 6",
            NumberOfCredits: "8",
        },

        obligatory: {
            title: "Học phần bắt buộc",
            NumberOfCredits: "6",
            section: [
                {
                    nameCourse: 'Tư tưởng Hồ Chí Minh',
                    code: "0101010038",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Giáo dục quốc phòng - an ninh *',
                    code: "0101081134",
                    typeOf: "",
                    NumberOfCredits: "8(6, 2, 16)",
                    LT: "125",
                    TH: "40",
                    form: "Tự luận",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Tiếng Anh 5 *',
                    code: "0101081685",
                    typeOf: "",
                    NumberOfCredits: "3(3, 0, 6)",
                    LT: "45",
                    TH: "0",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Kỹ thuật soạn thảo văn bản, trình bày báo cáo',
                    code: "0101082455",
                    typeOf: "",
                    NumberOfCredits: "2(1,1,4)",
                    LT: "15",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Đồ án học phần 1',
                    code: "0101082495",
                    typeOf: "",
                    NumberOfCredits: "2(0,2,4)",
                    LT: "0",
                    TH: "60",
                    form: "Bảo vệ",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        },
        selfSelect: {
            title: "Học phần tự chọn",
            NumberOfCredits: "2",
            section: [
                {
                    nameCourse: 'Kỹ năng làm việc nhóm',
                    code: "0101083026",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Kỹ năng quản lý thời gian',
                    code: "0101083027",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Kỹ năng tìm việc',
                    code: "0101083028",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
                ,
                {
                    nameCourse: 'Kỹ năng phỏng vấn',
                    code: "0101083029",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        }
    },
    {
        term: {
            title: "Học kỳ 7",
            NumberOfCredits: "16",
        },

        obligatory: {
            title: "Học phần bắt buộc",
            NumberOfCredits: "7",
            section: [
                {
                    nameCourse: 'Lập trình hướng đối tượng',
                    code: "0101081499",
                    typeOf: "",
                    NumberOfCredits: "3(2,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Tiếng Anh 6 *',
                    code: "0101081709",
                    typeOf: "",
                    NumberOfCredits: "3(3, 0, 6)",
                    LT: "45",
                    TH: "0",
                    form: "Tự luận",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Thực tập cơ sở',
                    code: "0101082453",
                    typeOf: "",
                    NumberOfCredits: "4(0,4,10)",
                    LT: "",
                    TH: "120",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },

            ]
        },
        selfSelect: {
            title: "Học phần tự chọn",
            NumberOfCredits: "9",
            section: [
                {
                    nameCourse: 'Tiếng Anh kỹ thuật',
                    code: "0101081133",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Lịch sử mỹ thuật',
                    code: "0101082940",
                    typeOf: "",
                    NumberOfCredits: "3(3,0,6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Nguyên lý thống kê',
                    code: "0101081085",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "1",
                    NumberTC: "5",
                }
                ,
                {
                    nameCourse: 'Kỹ thuật điện tử',
                    code: "0101081143",
                    typeOf: "",
                    NumberOfCredits: "2(2, 0, 4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "1",
                    NumberTC: "5",
                },
                {
                    nameCourse: 'Nguyên lý kế toán',
                    code: "0101081199",
                    typeOf: "",
                    NumberOfCredits: "3(3, 0, 6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "1",
                    NumberTC: "5",
                },
                {
                    nameCourse: 'Hệ thống thông tin quản lý',
                    code: "0101081466",
                    typeOf: "",
                    NumberOfCredits: "3(3, 0, 6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "1",
                    NumberTC: "5",
                },
                {
                    nameCourse: 'Lập trình Windows',
                    code: "0101081503",
                    typeOf: "",
                    NumberOfCredits: "3(2, 1, 6)",
                    LT: "30",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "1",
                    NumberTC: "5",
                },
                {
                    nameCourse: 'Thiết kế đồ hoạ 2',
                    code: "0101081557",
                    typeOf: "",
                    NumberOfCredits: "2(1, 1, 4)",
                    LT: "15",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "1",
                    NumberTC: "5",
                },
                {
                    nameCourse: 'Tin học chuyên ngành Đồ họa',
                    code: "0101081968",
                    typeOf: "",
                    NumberOfCredits: "2(1, 1, 4)",
                    LT: "15",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "1",
                    NumberTC: "5",
                },
                {
                    nameCourse: 'Luật xa gần',
                    code: "0101082513",
                    typeOf: "",
                    NumberOfCredits: "3(3,0,6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "1",
                    NumberTC: "5",
                },
                {
                    nameCourse: 'Lịch sử thiết kế đồ họa',
                    code: "0101082458",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "35",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "2",
                    NumberTC: "2",
                }
            ]
        }
    },
    {
        term: {
            title: "Học kỳ 8",
            NumberOfCredits: "7",
        },

        obligatory: {
            title: "Học phần bắt buộc",
            NumberOfCredits: "5",
            section: [
                {
                    nameCourse: 'Tiếng Anh B1.1',
                    code: "0101081887",
                    typeOf: "",
                    NumberOfCredits: "3(3,0,6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Linux và phần mềm mã nguồn mở',
                    code: "0101082459",
                    typeOf: "",
                    NumberOfCredits: "2(1,1,4)",
                    LT: "15",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }

            ]
        },
        selfSelect: {
            title: "Học phần tự chọn",
            NumberOfCredits: "2",
            section: [
                {
                    nameCourse: 'Văn hóa doanh nghiệp',
                    code: "0101081568",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Tâm lý học quản lý',
                    code: "0101082911",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        }
    },
    {
        term: {
            title: "Học kỳ 9",
            NumberOfCredits: "12",
        },

        obligatory: {
            title: "Học phần bắt buộc",
            NumberOfCredits: "12",
            section: [
                {
                    nameCourse: 'Tiếng Anh B1.1',
                    code: "0101081887",
                    typeOf: "",
                    NumberOfCredits: "3(3,0,6)",
                    LT: "45",
                    TH: "0",
                    form: "Trắc nghiệm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Hình họa khối cấu trúc cơ bản',
                    code: "0101082457",
                    typeOf: "",
                    NumberOfCredits: "3(2,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Thiết kế logo',
                    code: "0101082468",
                    typeOf: "",
                    NumberOfCredits: "2(1,1,4)",
                    LT: "15",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Thiết kế Catalogue, Brochure, tờ rơi, tờ gấp',
                    code: "0101082471",
                    typeOf: "",
                    NumberOfCredits: "2(1,1,4)",
                    LT: "15",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Thiết kế Áp phích thương mại',
                    code: "0101082472",
                    typeOf: "",
                    NumberOfCredits: "2(1,1,3)",
                    LT: "15",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }


            ]
        },
        selfSelect: {
            title: "Học phần tự chọn",
            NumberOfCredits: "2",
            section: [

            ]
        }
    },
    {
        term: {
            title: "Học kỳ 10",
            NumberOfCredits: "14",
        },

        obligatory: {
            title: "Học phần bắt buộc",
            NumberOfCredits: "8",
            section: [
                {
                    nameCourse: 'Đồ án học phần 2',
                    code: "0101081415",
                    typeOf: "",
                    NumberOfCredits: "2(0,2,4)",
                    LT: "0",
                    TH: "30",
                    form: "Bảo vệ",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Thiết kế bao bì sản phẩm',
                    code: "0101082470",
                    typeOf: "",
                    NumberOfCredits: "3(2,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Lập trình Python',
                    code: "0101083012",
                    typeOf: "",
                    NumberOfCredits: "3(2,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }

            ]
        },
        selfSelect: {
            title: "Học phần tự chọn",
            NumberOfCredits: "6",
            section: [
                {
                    nameCourse: 'Tổng quan về ý tưởng thiết kế',
                    code: "0101082031",
                    typeOf: "",
                    NumberOfCredits: "2(2,0,4)",
                    LT: "30",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Nghệ thuật sử dụng chữ',
                    code: "0101082006",
                    typeOf: "",
                    NumberOfCredits: "2(1,1,4)",
                    LT: "15",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Thiết kế nội bộ văn phòng',
                    code: "0101082469",
                    typeOf: "",
                    NumberOfCredits: "2(1,1,4)",
                    LT: "15",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Thiết kế trình bày sách báo',
                    code: "0101082487",
                    typeOf: "",
                    NumberOfCredits: "3(2,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Thiết kế lịch',
                    code: "0101082488",
                    typeOf: "",
                    NumberOfCredits: "3(2,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Thiết kế quảng cáo sự kiện',
                    code: "0101082489",
                    typeOf: "",
                    NumberOfCredits: "3(2,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Nghệ thuật nhiếp ảnh',
                    code: "0101082490",
                    typeOf: "",
                    NumberOfCredits: "2(1,1,4)",
                    LT: "15",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Thiết kế tem',
                    code: "0101082491",
                    typeOf: "",
                    NumberOfCredits: "2(1,1,4)",
                    LT: "15",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Áp phích cổ động chính trị xã hội',
                    code: "0101082492",
                    typeOf: "",
                    NumberOfCredits: "2(1,1,4)",
                    LT: "15",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Thiết kế nhân vật',
                    code: "0101082944",
                    typeOf: "",
                    NumberOfCredits: "3(1,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Tạo chuyển động trong môi trường 3D',
                    code: "0101082945",
                    typeOf: "",
                    NumberOfCredits: "3(1,1,6)",
                    LT: "30",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Thiết kế đồ họa Game',
                    code: "0101082946",
                    typeOf: "",
                    NumberOfCredits: "2(1,1,4)",
                    LT: "15",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Thiết kế giao diện Web',
                    code: "0101082947",
                    typeOf: "",
                    NumberOfCredits: "2(1,1,4)",
                    LT: "30",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                }
            ]
        }
    },
    {
        term: {
            title: "Học kỳ 11",
            NumberOfCredits: "10",
        },

        obligatory: {
            title: "Học phần bắt buộc",
            NumberOfCredits: "4",
            section: [
                {
                    nameCourse: 'Thực tập kỹ thuật',
                    code: "0101082942",
                    typeOf: "",
                    NumberOfCredits: "4(0,4,8)",
                    LT: "0",
                    TH: "120",
                    form: "Chấm sản phẩm",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
               

            ]
        },
        selfSelect: {
            title: "Học phần tự chọn",
            NumberOfCredits: "6",
            section: [
                {
                    nameCourse: 'Chuyên đề',
                    code: "0101081992",
                    typeOf: "",
                    NumberOfCredits: "3(0,3,6)",
                    LT: "0",
                    TH: "90",
                    form: "Bảo vệ",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Hệ thống nhận diện thương hiệu',
                    code: "0101082522",
                    typeOf: "",
                    NumberOfCredits: "4(3,1,8)",
                    LT: "45",
                    TH: "30",
                    form: "Thực hành",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                {
                    nameCourse: 'Đồ án tốt nghiệp cử nhân',
                    code: "0101082523",
                    typeOf: "",
                    NumberOfCredits: "2(0,4,8)",
                    LT: "0",
                    TH: "180",
                    form: "Bảo vệ",
                    typeOfLecture: "",
                    group: "0",
                    NumberTC: "",
                },
                
            ]
        }
    },
]
export default TERM_DESIGN